canonical/sdcore-nms

components/CreateSubscriberButton.tsx, components/DeleteSubscriberButton.tsx, components/EditSubscriber.tsx, components/NetworkConfiguration.tsx, components/SubscriberTable.tsx, config/sdcoreConfig.ts, hooks/useSubscriber.tsx, pages/api/createNetworkSlice.ts, pages/api/createSubscriber.ts, pages/api/deleteSubscriber.ts, pages/api/getSubscribers.ts
This implements client/server side separation. The main idea is that the browser should not communicate directly with webui, both for security and ease-of-life reasons. The client side now only communicates with the server side and the server side has the ability to communicate with `webui`.
The following environment variables now need to be set for running the server:
- WEBUI_ENDPOINT
- UPF_HOSTNAME
- UPF_PORT
Those as well as the rest of the config are now only available to the server.
This change will make it possible that the only components that need to be accessible from the outside world is the gui (and not webui).
=> [Feat] Separates client from server functionality

.github/workflows/integration_tests.yaml, .github/workflows/main.yaml, .github/workflows/publish.yaml, CONTRIBUTING.md, README.md, next.config.js, rockcraft.yaml
The container image used to be maintained independently in [sdcore-gui-rock](https://github.com/canonical/sdcore-gui-rock). This PR moves the rock management to this project instead. This includes both the `rockcraft.yaml` file itself and the CI to publish it.
=> [Feat] Adds container image to project

rockcraft.yaml
Doesn't use working-dir in pebble layer because the Pebble version that juju uses doesn't support it yet. This should be fixed in Juju 3.1.6
Reference
- https://github.com/canonical/operator/issues/988
Having the pebble layer like it was made the GUI charm crash before being able to ovewrite the pebble layer:
```
Traceback (most recent call last):
File "/var/lib/juju/agents/unit-sdcore-gui-0/charm/./src/charm.py", line 147, in <module>
main(SDCoreGUIOperatorCharm)
File "/var/lib/juju/agents/unit-sdcore-gui-0/charm/venv/ops/main.py", line 439, in main
framework.reemit()
File "/var/lib/juju/agents/unit-sdcore-gui-0/charm/venv/ops/framework.py", line 851, in reemit
self._reemit()
File "/var/lib/juju/agents/unit-sdcore-gui-0/charm/venv/ops/framework.py", line 930, in _reemit …
```
=> [Bug fix] Doesn't use working-dir in pebble layer

.github/workflows/main.yaml
Adds build step before integration tests in CI. This makes it quicker to observe issues with the build and removes the need to set up rockcraft to notice that the project doesn't build.
=> [Feat] Adds build step before integration tests in CI

components/DeviceGroupModal.tsx, utils/createDeviceGroup.tsx
Uses bps instead of Mbps for webui communication. Using Mbps provided inconsistent responses from webui where when users were added to a device group, the bitrate return value would change.
Fixes #113
=> [bug fix] Uses bps instead of Mbps for webui communication

app/network-configuration/page.tsx, components/CreateNetworkSliceModal.tsx, components/NetworkSliceEmptyState.tsx
Adds a confirmation modal when deleting network slice.
=> [feat] Adds confirmation modal when deleting network slice

app/subscribers/page.tsx, components/NetworkSliceTable.tsx, package-lock.json, package.json
The main idea here is to have all our icons come from 1 source and this PR standardises icon styling by using material UI which is the most widely used source of icons. There used to be 2 sources:
- Canonical: Chevrons and plus
- React: Refresh
This standardisation will become even more useful when adding the "edit" button which does not exist in [Canonical's react components](https://canonical.github.io/react-components/?path=/docs/icon--base#default). 
- https://mui.com/material-ui/material-icons/
=> chore: Uses material UI for icons

rockcraft.yaml
This PR improves the rock in various way:
- Adds pebble service for nms
- Uses the same nodejs source for build and stage instead of having a ppa in a snap. This source is now the official ppa repo with gpg key validation instead of being a binary. Note that we can't use the snap because of [this bug](https://github.com/canonical/rockcraft/issues/307) in rockcraft. This removes the need for the "node" part.
- Removes unnecessary stage of package-lock.json
=> chore: Adds pebble service to rockcraft

components/CreateNetworkSliceModal.tsx
This PR fixes a NMS crash on Network Slice creation.
The crash happened when GNBs config file was missing or did not contain any GNB.
The error provoke and infinite loop of rendering. The problem was fixed using React Effects.
The same problem was identified and fixed for the UPFs config file. 
In case the config files are missing or there are no GNBs or UPFs. An error message is shown as:
=> fix: NMS crash when GNBs config file is missing

components/CreateSubscriberModal.tsx, pages/api/subscriber/index.ts, utils/createSubscriber.tsx
There is an issue where the subscribers page crashes when webui returns nil. This PR makes it so that when that occurs, an empty list is returned instead making the page render correctly.
=> fix: Subscriber page crashes when webui returns nil

.github/workflows/publish.yaml
PR #197 introduced an unnecessary `"` at the end of the `docker push` command which caused failures in publishing the NMS image to ghcr. This PR fixes this issue.
=> fix: Removes typo in CI docker push

components/NetworkSliceTable.tsx
Just like we display the total number of network slices and subscribers in parenthesis (example: `Network Slices (3)`), we now do the same for device groups.
=> feat: Adds total number of device groups

utils/deleteSubscriber.tsx
We used to delete subscribers by calling `subscriber/<imsi>` which would partially work but a subscriber with no name would remain and would result in a "ghost" subscriber in the subscriber table. The right way to delete subscribers is by calling `subscriber/imsi-<imsi>`. 
Fixes #201
=> fix: Deletes subscribers using `imsi-` prefix

components/CreateNetworkSliceModal.tsx
The network slice creation modal use to consider MCC's and MNC's starting with zero's as invalid. This PR fixes this problem by considering those entries as text instead of numbers.
Fixes #196
=> fix: Treats mcc and mnc as text instead of numbers

utils/createNetworkSlice.tsx
This is a fix for https://github.com/canonical/sdcore-nms/issues/222
After https://github.com/canonical/sdcore-nms/pull/200 we create a `default` Device Group when we create a NS.
The same name was used for every NS created, which resulted in only one Device Group. 
When we deleted a NS, the `default` Device Group was deleted as well, resulting in the delete of all the subscribers associated to this `default` Device Group, even if they belonged to another NS. 
A fix for this is to use the name of the NS in the name of the default Device Group created at the NS creation time:
`deviceGroupName = ${name}-default`. This way, we can guarantee that the Device Group name is unique at the moment.
There is a task in the backlog  called: "Validate that device group doesn't yet exist before creating …
=> fix: NS deletes subscribers that belong to other NS

utils/createNetworkSlice.tsx
Uses default mtu of 1460 instead of 1600 and transposes uplink/downlink bitrates.
=> fix: Uses default mtu of 1460

rockcraft.yaml
The `/pages` directory was not copied over in the final ROCK image. This directory contains the swagger definitions needed to display the API documentation.
Fixes #229
=> fix: Include pages directory in final image

components/CreateNetworkSliceModal.tsx, components/DeviceGroupModal.tsx, pages/api/device-group/[name].ts, pages/api/network-slice/[name].ts, utils/createDeviceGroup.tsx, utils/createNetworkSlice.tsx
We now validate whether a network slice (and device group) with the same name already exists before creating it. If it already exists, it is displayed to the user in the creation modal.
Fixes #231
=> feat: Adds input validation to network slices and device groups

components/CreateSubscriberModal.tsx, pages/api/device-group/[name].ts, pages/api/subscriber/[name].ts, utils/createSubscriber.tsx
We now validate whether a subscriber with the same name already exists before creating it. If it already exists, an error is displayed to the user in the creation modal.
There is an issue with the CURL GET of subscribers  (https://github.com/omec-project/webconsole/issues/109) in which an "empty" subscriber object is returned if the subscriber does not exists. So, as a workaround I added a check over one of the fields to be able to differentiate between a subscriber that exists and one that does not.
=> feat: Prevent duplicated subscribers creation

.gitignore, app/_pattern_navigation.scss, components/DeviceGroupModal.tsx, components/NetworkSliceGroups.tsx, components/NetworkSliceTable.tsx, utils/editDeviceGroup.tsx
Adds possibility of editing existing device groups.
Device group edition modal uses the same layout as the creation modal. 
Validation is the same. 
It is not possible to edit device group name.
=> feat: Adding device group edition feature

app/(network)/network-configuration/page.tsx, components/NetworkSliceEmptyState.tsx, components/NetworkSliceModal.tsx, components/types.tsx, utils/editNetworkSlice.tsx, utils/queryKeys.tsx
Adds the possibility to edit network slices.
Takes advantage of the existing Create Network Slice Modals and change the display of the fields according to the action (create or edit)
The fields in the modal are pre filled with the values of the Network Slices.
REST PATCH method does not work in the webui so I am getting the Network Slice object, modifying the new field values and POST it again. 
It is not possible to edit the name of the Network Slice
=> feat: Edit network slice

utils/deleteSubscriber.tsx
fix https://github.com/canonical/sdcore-nms/issues/412 
The `imsis` field of a new NS that has never had a subscriber associated  is `null`
When a NS has already had a subscriber associated the field is `[]`
We were assuming that this field was always `[]` so it failed trying to access a `null` value. In consequence the subscriber was not entirely deleted.
=> fix:  null error when deleting subscriber

.github/workflows/issues.yaml
Use the release version of sdcore-github workflows instead of using the main branch.
This will allow to make breaking changes in the workflows without breaking its dependents. More specifically, we are working on building the charm in its independent workflow step instead of having it built in the integration tests. Making such change in the workflows would break every NF CI until they adapt to the new workflow approach. Here we want to avoid this and have the workflow keep on working until we intentionally adopt the new approach.
=> chore: use release version of sdcore github workflows

utils/editSubscriber.tsx
fix https://github.com/canonical/sdcore-nms/issues/509
pop method in arrays does not work as expected.
To remove a specific element we need to know the index.
=> fix: edit subscriber

.github/workflows/issues.yaml
Revert commit automatically merged by telcobot
This reverts commit 573d7a0bcf2038806afe82b239c1f2c78ca5fe8e.
Please include a summary of the change. Please also include relevant motivation and context. List any dependencies that are required for this change.
=> chore: revert Bump canonical/sdcore-github-workflows from 0.0.1 to 0.02

.github/workflows/main.yaml
Workflows for main branch CI does not run when a PR is opened. This will fix the issue.
=> fix: run CI workflows when a PR is created

.github/workflows/integration_tests.yaml, .github/workflows/publish.yaml
The version of skopeo that is delivered in the snap has not been updated since 2019. Recently, jobs that use skopeo have been failing with the following message:
`writing blob: saving image to docker engine: client version 1.22 is too old. Minimum supported API version is 1.24, please upgrade your client to a newer version`
N/A I have made corresponding changes to the documentation.
N/A Any dependent changes have been merged and published in downstream modules.
=> fix: use newer skopeo

CONTRIBUTING.md
Rockcraft now ships an updated version of skopeo that works with docker 1.24 and higher
=> fix: updating instructions to use rockcraft.skopeo

components/NetworkSliceModal.tsx
Modifying the MNC or the MCC fields of a Network Slice creates a duplicate subscriber (unexpected behavior). https://github.com/omec-project/webconsole/issues/200
This workaround disables the possibility of editing the MNC and MCC fields of a network slice. 
Editing the gNB or the UPF works fine. 
Edit Network Slice Modal:
Create Network Slice Modal: (no changes here)
=> fix: workaround for edit NS bug

components/Navigation.tsx, rockcraft.yaml
The swagger UI API link was disabled, while waiting for the upstream webconsole implementation to be merged (https://github.com/omec-project/webconsole/pull/193) 
This PR re enables the link and update the upstream webconsole version.
=> fix: re enable API link to swagger UI

utils/createNetworkSlice.tsx
Value of the Slice Differentiator (SD) needs to represent a 24-bit integer and needs to have an even number of digits. 
This PR fixes the default value of the SD.
In the longer run both SD and SST should probably be configurable.
=> fix: Fixes the value of the Slice Differentiator to represent a valid 24-bit int

app/(network)/network-configuration/page.tsx, components/NetworkSliceGroups.tsx, components/NetworkSliceModal.tsx, components/NetworkSliceTable.tsx, components/SubscriberModal.tsx, components/types.tsx
https://github.com/omec-project/webconsole/pull/244 introduces a name change in the backend which is  `NetworkSlice`  to `network-slice`. Another change is done in the backend: https://github.com/omec-project/webconsole/pull/248 to fix the DB operation. The change in the Slice name also broke the front-end and `name` does not appear in the slices and device groups does not appear in the subscribers. 
This patch fixes the issue.
=> fix: change SliceName to slice-name because of replacement in the backend

app/(nms)/users/page.tsx
https://github.com/canonical/sdcore-nms-k8s-operator/pull/359 enables authentication in the NMS charm. The charm creates an admin user and stores its username and password in a Juju secret. If the admin's password is updated using the NMS UI, the charm will loose the admin user's credentials and it will not be able to operate over the webconsole. 
**This is not a final solution to the problem.**
The button to change password is enabled:
The button to change password is disabled for the admin user:
The button to change password is enabled for the not admin user:
=> chore: disable password change button for admin user

CONTRIBUTING.md, README.md, components/NetworkSliceGroups.tsx, components/NetworkSliceModal.tsx, components/NetworkSliceTable.tsx, utils/editNetworkSlice.tsx
https://github.com/omec-project/webconsole/pull/279 propagates the DELETE UPF operation to  network slices to avoid dangling references. If a UPF is removed from a NS, this field no long exists and if we try to edit the NS, the NMS crashes. This PR adds support for network slices that do not contain a "upf" field.
After this PR, the NMS no longer crashes, instead, the UPF value selected by default in the Edit modal is empty.
After this PR, the empty fields are shown as empty instead of `N/A`. Also the name of the device groups are no longer cast to capital letters.
This PR also adds minor fixes to the CONTRIBUTING.md and README.md files
=> feat: support empty UPF field in NS

components/SubscriberModal.tsx, utils/editSubscriber.tsx
The GetSubscribers operation will get the information from `subscriptionData.provisionedData.amData`.
The GET subscriber by ID operation returns an union of several DB fields. Some of them can be absent depending on the order of creation of the subscriber (first create DG and then subscriber, or the other way around).
if `subscriptionData.provisionedData.amData` exist but the others don't, the subscriber will appear in the list of subscribers and  if we try to edit it, the NMS will crash.
This PR remove the crash in case of missing `AuthenticationSubscription` fields in a Subscriber.
It modifies the workaround to identify if a Subscriber does not exist (https://github.com/omec-project/webconsole/issues/109) to check if both `AuthenticationSubscription/authenticationMethod and …
=> fix: avoid crash when fields in subscriber are missing

components/SubscriberModal.tsx
back port https://github.com/canonical/sdcore-nms/pull/723 and a part of https://github.com/canonical/sdcore-nms/pull/707
fix for https://github.com/canonical/sdcore-nms/issues/711 and https://github.com/canonical/sdcore-nms/issues/712
Issue: we cannot create/edit subscribers in network slices that contain more than 1 device group. We are not able to select an element of the dropdown.
=> fix: backport fix subscriber modal

utils/createNetworkSlice.tsx
In the webconsole, the creation of NS and DG are really tight and need an specific order. 
1. When we create a NS that contains a reference to a DG that does not exist:
- a broken message is sent to the PCF
- there is an error and no message is sent to the other NFs
3. When we create a DG  no message is sent to the PCF. (it's only sent on update or delete DG operation)
4. When we create a DG and there are no network slices, no message is sent to NFs.
Current behavior in the NMS when creating a NS:
- POST NS with a reference to a non-existing DG
- POST a DG associated to that NS
If we do this, we run into situation 1. and we can see the following logs, when sending the config messages to other NFs trough GRPC:
```
025-02-05T09:03:04.947Z [nms] 2025-02-05T09:03:04.947Z	INFO …
```
=> fix: reorder creation of Network slice objects

components/NetworkSliceModal.tsx
This is a fix for https://github.com/canonical/sdcore-nms-k8s-operator/issues/440
**Before**: every time we clicked in a gnb option, it was added to the form values (even if it already was selected).
**Now**: we add all the selected values to the form values, they are replaced at each change. We need to use `ctrl` to select multiple gnbs. This is the behavior that we see in https://vanillaframework.io/docs/base/forms#select
=> fix: select gnb list in Network slice modal error

app/(nms)/subscribers/modals.tsx
In the previous version, there was a lot of extra (unnecessary) space in the input fields of the modal.
This PR reduces this space.
The use of `label` instead of just `div` for the plmnID helps with the alignment.
The key to solve this problem : `style={{ display : "flex" }}`
=> fix: subscriber modal size

app/(nms)/subscribers/modals.tsx, rockcraft.yaml, utils/errors.tsx, utils/subscriberOperations.tsx, utils/utils.ts
The backend started to throw `Not Found Error` if subscriber does not exist and `Conflict Error` if subscriber already Exist within the following PRs:
https://github.com/omec-project/webconsole/pull/318
https://github.com/omec-project/webconsole/pull/317
This PR handles those errors in the frontend which are throwed by backend.
=> fix: handle 404 no found and 409 conflict errrors during subscriber operations

app/(nms)/network-configuration/modals.tsx, app/(nms)/network-configuration/page.tsx
This PR improves the Network Slice modal by preventing the selection of invalid gNBs (those without an associated TAC).
=> feat: allow selecting only valid gNBs in network slice modal

README.md, package.json, rockcraft.yaml
Bump NMS workload to the latest upstream webconsole release v1.8.5.
Bump the `go` version to the same as used in the upstream project: 1.24.
=> chore: bump workload to v1.8.5

app/(nms)/inventory/gnbs_modals.tsx, app/(nms)/network-configuration/modals.tsx, package-lock.json
This PR fixes #784 adding an helper message informing the users that a gNB may not be seen in the Network Slice modal when it has no TAC associated to it.
This PR also improves the name validation of gNBs by limiting the maximum length to 256 characters (as enforced in `webconsole` backend).
=> chore: inform users on missing gNBs in Network Slice model

app/(nms)/device-groups/modals.tsx
Fix https://github.com/canonical/sdcore-nms/issues/770
The input field for numbers in MBR upstream, MBR downstream and MTU does not allow anymore to set values outside of the valid range using the mouse.
=> fix: allowed values in number inputs

app/(nms)/subscribers/modals.tsx
Fix https://github.com/canonical/sdcore-nms/issues/787
This PR adds a help message in the Network slice field in the edit subscriber modal, to inform that only those using compatible MCC and MNC are listed.
No changes in the create modal
=> fix: add help message in subscriber edit modal (network slice field)
