components/CreateSubscriberButton.tsx, components/CreateSubscriberModal.tsx, components/NetworkConfiguration.tsx, components/SubscriberTable.tsx
Adds user input validation for MCC, MNC, IMSI, OPC and Key.
=> [Feat] Adds user input validation

app/subscribers/page.tsx
[Bug fix] Fetch subscribers is called every time refresh is triggered
=> [Bug fix] Fetch subscribers is called every time refresh is triggered

.github/workflows/integration_tests.yaml, CONTRIBUTING.md, README.md, app/layout.tsx, app/page.tsx, package-lock.json, package.json, rockcraft.yaml
Changes project name from sdcore-gui to sdcore-nms. Once this PR is merged, the github project name will also be updated.
=> [Chore] Changes project name from sdcore-gui to sdcore-nms

app/layout.tsx
Adds sticky footer with documentation, legal info and github issues link
=> [feat] Adds sticky footer

CONTRIBUTING.md, README.md, package-lock.json, package.json, rockcraft.yaml
=> [chore] Uses semantic versioning

app/subscribers/page.tsx
Adds confirmation modal when deleting subscribers
=> [feat] Adds confirmation modal when deleting subscribers

app/layout.tsx
Displays selected navigation item.
=> feat: Displays selected navigation item

app/layout.tsx, app/network-configuration/page.tsx, app/subscribers/page.tsx, components/CreateNetworkSliceModal.tsx, components/CreateSubscriberModal.tsx, components/DeleteSubscriberButton.tsx, components/DeviceGroupModal.tsx, components/Loader.tsx, components/NetworkSliceEmptyState.tsx, components/NetworkSliceGroups.tsx, components/NetworkSliceTable.tsx, package-lock.json, package.json, utils/checkBackendAvailable.tsx, utils/checkNetworkSliceExists.tsx, utils/createNetworkSlice.tsx, utils/getDeviceGroup.tsx, utils/getGnbList.tsx, utils/getNetworkSlice.tsx, utils/getNetworkSlices.tsx, utils/getSubscribers.tsx, utils/getUpfList.tsx, utils/queryKeys.tsx
* added useQuery dependency for easier loading of data
* adjusted all data loading to useQuery instead of useEffect
* added formik dependency for easier form handling
* added yup dependency for easier form validation
* adjusted all forms to use formik
* design: added consistent loading states to pages
* design: adjusted margin of buttons
* design: adjusted headings to be h1 / h2 and render a bit smaller
* design: removed chip from the subscribers page and add the number of items to the headings
* started using ConfirmationButton component where it simplifies code
* started using ActionButton to make loading of submitted forms visible
=> Refactor loading with useQuery and adopt formik for form data

.github/workflows/lint-pr.yaml
Adds semantic PR name validation using this project: https://github.com/amannn/action-semantic-pull-request/tree/v5/
=> chore: Adds semantic PR name validation

app/_pattern_navigation.scss, app/globals.scss, app/layout.tsx, app/network-configuration/page.tsx, app/subscribers/page.tsx, components/Logo.tsx, components/Navigation.tsx, components/PageContent.tsx, components/PageHeader.tsx
* use application layout with side navigation
* apply consistent loading indicators
* add favicon
=> feat: Use application layout

.github/workflows/integration_tests.yaml
Fixes integration tests by looking for "5G NMS" in the html page.
=> fix: Fixes integration tests

components/NetworkSliceModal.tsx
Set "Save Changes" in the button for edit network slice modal
=> chore: set save changes in edit network slice button

components/Navigation.tsx
Update links to documentation following product renaming.
=> chore: Update links to documentation

rockcraft.yaml
Bump the base to Ubuntu 24.04.
=> chore: use ubuntu 24.04 base

.github/workflows/main.yaml
Use branch name in the workflows.
=> chore: use branch name in the workflows

rockcraft.yaml
This PR updates the version of webconsole used to include the HTTPS feature.
=> feat: add https feature for NMS

components/SubscriberModal.tsx, rockcraft.yaml
Here we include all dependencies in the useEffect hook, removing the warning occuring at build time.  
Fixes #617
=> fix: include all dependencies in useEffect hook

.github/dependabot.yml, .github/workflows/1_0_0_scheduled_runs.yaml, .github/workflows/build-nms.yaml, .github/workflows/codeql-analysis.yaml, .github/workflows/nms-lint-report.yaml, README.md, package-lock.json, package.json, rockcraft.yaml
- Bump rock and upstream version after branching
- Adds scheduled CI runs for `v1.0.0` branch
=> chore: Bump rock and upstream version after branching

.github/workflows/main.yaml
Fixes duplicate CI triggers and running `push` jobs on pull requests. Also updates the version of the workflow.
=> fix: Fix duplicate CI triggers

CONTRIBUTING.md
Fix a typo in the contributing file
=> fix: fix typo

Makefile
After https://github.com/omec-project/webconsole/pull/279 we need MongoDB deploy as a Replica Set. This PR updates the deploy command in the Makefile for local development.
=> feat: locally deploy MongoDB as replica set

package-lock.json, package.json, postcss.config.js
This PR updates dependencies and fix issue with tailwindcss that was blocking dependedabot update. https://github.com/canonical/sdcore-nms/pull/734
Same as https://github.com/canonical/sdcore-nms/pull/722 for main
=> chore: update dependencies and fix issue with tailwindcsss

app/(nms)/layout.tsx, package-lock.json, package.json
This PR updates the version of `react-cookie` and makes the changes needed to use the new version: wrap the app with `<CookiesProvider>`
this fixes the build issue in https://github.com/canonical/sdcore-nms/pull/772
=> chore: bump react-cookie dependency

.github/workflows/1_0_0_scheduled_runs.yaml, .github/workflows/issues.yaml, .github/workflows/main.yaml
Use the updated scan-rock workflow which compares the KEV database with the current CVEs and show them in the security tab.
=> feat: find and show KEV vulnerabilities
